<a href="https://colab.research.google.com/github/SaashaJoshi/tf-keras-examples/blob/master/PyTorch_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
def sigmoid_activation(x):
  return 1/(1+ torch.exp(-x))

In [ ]:
torch.manual_seed(100)  # Setting seed to produce random numbers

# Weights:(1xn) Inputs: (nx1) Bias:(1x1)
inputs = torch.randn((1, 5))    # rand-n for random normal variables
print(inputs)

weights = torch.randn_like(inputs)
print(weights)

bias = torch.randn((1, 1))
print(bias)

# The randn feature generates random numbers which form a normal distribution with variance 1 and mean 0. This distribution is also called Standard Normal Distribution.

tensor([[ 0.3607, -0.2859, -0.3938,  0.2429, -1.3833]])
tensor([[-2.3134, -0.3172, -0.8660,  1.7482, -0.2759]])
tensor([[-0.9755]])


In [ ]:
inputs.resize_((5, 1))    # Resize in-place i.e. changes the mentioned tensor

# Or use inputs.reshape(5, 1)  # This returns a new tensor
# Or inputs.view(5, 1)         # This returns a new tensor but doesn't mess with the data

# Tip: Dot Product is Commutative
y = sigmoid_activation(torch.mm(weights, inputs) + bias)
print(y)

tensor([[0.3608]])


In [ ]:
wx = torch.mm(weights, inputs)
y_dash = sigmoid_activation(wx + bias)
print(y_dash)

tensor([[0.3608]])


In [ ]:
wx = torch.sum(weights*inputs)
y_dash = sigmoid_activation(wx + bias)
print(y_dash)   # Disparity!! Check this!

tensor([[0.8786]])


In [ ]:
y = sigmoid_activation(torch.mm(inputs, weights.view(5, 1)) + bias)   # Commutative property here!
print(y)

tensor([[0.3608]])


In [ ]:
torch.manual_seed(100)

# 2 Layered NN with 1 hidden layer consisting of 2 hidden neurons and 1 output layer consisting of 1 neuron.

# Hidden Layer 1: W(2x3) I(3x1) B(2x1)
# Output Layer: W(1x2) I(2x1) B(1x1)
X = torch.randn((3, 1))     # Inputs

n_inputs = X.shape[0]
n_hidden1_neurons = 2
n_output_neurons = 1

# Weights
W1 = torch.randn((n_hidden1_neurons, n_inputs))    # Matrix of weights of hidden layer 1 i.e. [w11_T]
                                                                                  #           [w12_T]       
W2 = torch.randn((n_output_neurons, n_hidden1_neurons))               # Matrix of weights of output layer i.e. [w21_T]
                                                                                                     #         [w22_T]      

# Bias
B1 = torch.randn((n_hidden1_neurons, 1))
B2 = torch.randn((n_output_neurons, 1))

In [ ]:
# Solution
Z1 = torch.mm(W1, X) + B1
A1 = sigmoid_activation(Z1)

Z2 = torch.mm(W2, A1) + B2
A2 = sigmoid_activation(Z2)

final_output = A2
print(final_output)

tensor([[0.2509]])
