<a href="https://colab.research.google.com/github/SaashaJoshi/tf-keras-pytorch-examples/blob/master/PyTorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# Uninitialized Matrix
x = torch.empty(5, 3)     # Contains values present in memory at that time.
print(x)

tensor([[1.0661e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.1657e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [ ]:
# Randomly initialized Matrix
x = torch.rand(5, 3)
print(x)

tensor([[0.3021, 0.1789, 0.5142],
        [0.2367, 0.2167, 0.2298],
        [0.8358, 0.1300, 0.4801],
        [0.8706, 0.5673, 0.2947],
        [0.0607, 0.1819, 0.7863]])


In [ ]:
# Zero matrix with dtype = long
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
x = torch.empty(5, 3, dtype = torch.long)     # dtype = long
print(x)

tensor([[    89659776, 206158430258, 206158430253],
        [193273528374, 223338299441, 210453397588],
        [249108103220, 219043332145, 223338299450],
        [197568495672, 210453397552, 227633266745],
        [210453397555, 493921239130, 176093659177]])


In [ ]:
# Tensor directly from data
x = torch.tensor([6, 7])
print(x)
print(x.size())

tensor([6, 7])
torch.Size([2])


In [ ]:
# Ones tensor
x = torch.ones(5, 3, dtype = torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [ ]:
# Create tensor form an existing tensor
x = x.new_ones(5, 3, dtype = torch.double)
print(x)

# Override dtype, size remains same (5, 3)
x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 2.7348, -0.6893, -1.1803],
        [ 0.2229,  0.7663,  1.3477],
        [-0.1324,  0.1565,  0.4190],
        [ 1.1139,  0.8697,  0.6361],
        [ 0.2051, -0.0085,  0.3909]])


In [ ]:
# Get size
print(x.size())

torch.Size([5, 3])


In [ ]:
# Addition
x = torch.rand(5, 3)
y = torch.rand(5, 3)

print(x)
print(y)

print(x + y)
print(torch.add(x, y))    # Alternative syntax 

tensor([[0.9084, 0.4482, 0.0231],
        [0.6727, 0.5643, 0.8350],
        [0.0378, 0.5967, 0.5468],
        [0.7319, 0.0875, 0.4767],
        [0.9016, 0.3127, 0.9319]])
tensor([[0.8312, 0.5289, 0.1373],
        [0.2709, 0.8023, 0.2702],
        [0.2893, 0.5841, 0.5363],
        [0.4745, 0.0983, 0.4955],
        [0.9867, 0.8178, 0.0484]])
tensor([[1.7395, 0.9770, 0.1604],
        [0.9436, 1.3666, 1.1052],
        [0.3271, 1.1808, 1.0831],
        [1.2064, 0.1858, 0.9723],
        [1.8883, 1.1305, 0.9803]])
tensor([[1.7395, 0.9770, 0.1604],
        [0.9436, 1.3666, 1.1052],
        [0.3271, 1.1808, 1.0831],
        [1.2064, 0.1858, 0.9723],
        [1.8883, 1.1305, 0.9803]])


In [ ]:
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[1.7395, 0.9770, 0.1604],
        [0.9436, 1.3666, 1.1052],
        [0.3271, 1.1808, 1.0831],
        [1.2064, 0.1858, 0.9723],
        [1.8883, 1.1305, 0.9803]])


In [ ]:
# In-place addition
y.add_(x)
print(y)      # Changes y
# Operation which mutates a tensor in place is post-fixed with underscore(_) 

tensor([[1.7395, 0.9770, 0.1604],
        [0.9436, 1.3666, 1.1052],
        [0.3271, 1.1808, 1.0831],
        [1.2064, 0.1858, 0.9723],
        [1.8883, 1.1305, 0.9803]])


In [ ]:
print(y[:, :1])

tensor([[1.7395],
        [0.9436],
        [0.3271],
        [1.2064],
        [1.8883]])


In [ ]:
import numpy as np

In [ ]:
a = np.random.rand(4, 3)
a

array([[0.42180366, 0.15652495, 0.67078758],
       [0.69371059, 0.23374645, 0.00327953],
       [0.96268285, 0.87849741, 0.2557813 ],
       [0.97789144, 0.99785134, 0.40846873]])

In [ ]:
b = torch.from_numpy(a)
b

tensor([[0.4218, 0.1565, 0.6708],
        [0.6937, 0.2337, 0.0033],
        [0.9627, 0.8785, 0.2558],
        [0.9779, 0.9979, 0.4085]], dtype=torch.float64)

In [ ]:
b.numpy()

array([[0.42180366, 0.15652495, 0.67078758],
       [0.69371059, 0.23374645, 0.00327953],
       [0.96268285, 0.87849741, 0.2557813 ],
       [0.97789144, 0.99785134, 0.40846873]])

In [ ]:
b 

tensor([[0.4218, 0.1565, 0.6708],
        [0.6937, 0.2337, 0.0033],
        [0.9627, 0.8785, 0.2558],
        [0.9779, 0.9979, 0.4085]], dtype=torch.float64)

In [ ]:
# Memory is shared between numpy array (a) and tensor (b). Change in one will be reflected in other.
b.mul_(2)
b

tensor([[0.8436, 0.3130, 1.3416],
        [1.3874, 0.4675, 0.0066],
        [1.9254, 1.7570, 0.5116],
        [1.9558, 1.9957, 0.8169]], dtype=torch.float64)

In [ ]:
a

array([[0.84360731, 0.31304991, 1.34157515],
       [1.38742118, 0.46749291, 0.00655906],
       [1.9253657 , 1.75699483, 0.51156259],
       [1.95578288, 1.99570268, 0.81693747]])